branch-defaults:
  default:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: simplesocial-course
  branch: null
  default_ec2_keyname: uddap-ubuntu-keypair
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
